INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (1, 'Juan', 'Perez', 'jperez@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (2, 'Valeria', 'Alban', 'valban@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (3, 'Diego', 'Jacome', 'djacome@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (4, 'Marco', 'Perez', 'mperez@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (5, 'Hugo', 'Alban', 'halban@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (6, 'Marcela', 'Jacome', 'mjacome@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (7, 'Juan', 'Vivanco', 'jvivanco@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (8, 'Valeria', 'Lopez', 'vlopez@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (9, 'Diego', 'Rios', 'drios@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (10, 'Marco', 'Maza', 'mmaza@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (11, 'Hugo', 'Felix', 'hfelix@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (12, 'Marcela', 'Arauz', 'marauz@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (13, 'Andrea', 'Meza', 'ameza@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (14, 'Daniela', 'Fenix', 'dfenix@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (15, 'Juana', 'Diaz', 'jdiaz@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (16, 'Martin', 'Zurita', 'mzurita@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (17, 'Ricardo', 'Montaner', 'montaner@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (18, 'Diana', 'Tequila', 'dtequila@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (19, 'Enma', 'Maza', 'emaza@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (20, 'Jose', 'Sanchez', 'jose@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (21, 'Antonio', 'Rivera', 'arivera@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (22, 'Edson', 'Felix', 'efelix@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (23, 'Alex', 'Aguinaga', 'elalex@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (24, 'Diana', 'Flores', 'dflores@gmail.com', '2018-03-09', '');
INSERT INTO CLIENTES (id, nombre, apellido, email, create_at, foto) VALUES (25, 'Juan', 'Quilca', 'jquilca@gmail.com', '2018-03-09', '');

INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('Panasonic Pantalla LCD', 800, NOW());
INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('Sony Camara Digital DSC-W3200', 400, NOW());
INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('Apple iPod Shuffle', 200, NOW());
INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('Sony Notebook Z110', 500, NOW());
INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('HP Impresora Multifuncional', 170, NOW());
INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('MacbookPro Retina 2012', 900, NOW());
INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('Apple iPhone 8', 800, NOW());
INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('Apple iPhone X', 1500, NOW());
INSERT INTO PRODUCTOS (nombre, precio, create_at) VALUES ('Asus ROG 17 GTX 1080', 2000, NOW());

INSERT INTO FACTURAS (descripcion, observacion, cliente_id, create_at) VALUES ('Factura Laptops', null, 1, NOW());
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (1, 1, 4);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (1, 1, 6);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (1, 1, 9);

INSERT INTO FACTURAS (descripcion, observacion, cliente_id, create_at) VALUES ('Factura iPhones', null, 1, NOW());
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (2, 2, 7);
INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES (1, 2, 8);